# basic options
title: Garage Sale
author: Anthony & Heidrun
# email: your-email@domain.com
description: Selling stuff that's been lying around forever...

<form action="https://formspree.io/garagesale.ashs@gmail.comm">
    <input type="text" name="name">
    <input type="email" name="_replyto">
    <input type="submit" value="Send">
</form>s

# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
